/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Media = IDL.Variant({
  'imageUrl' : IDL.Text,
  'pptUrl' : IDL.Text,
  'videoUrl' : IDL.Text,
});
export const Clue = IDL.Record({
  'id' : IDL.Nat,
  'media' : IDL.Opt(Media),
  'title' : IDL.Text,
  'statement' : IDL.Text,
  'answer' : IDL.Text,
});
export const ClueSummary = IDL.Record({
  'id' : IDL.Nat,
  'media' : IDL.Opt(Media),
  'title' : IDL.Text,
  'statement' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const AnswerResult = IDL.Record({
  'correct' : IDL.Bool,
  'nextClueId' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllClues' : IDL.Func([], [], []),
  'createClue' : IDL.Func([Clue], [], []),
  'deleteClue' : IDL.Func([IDL.Nat], [], []),
  'editClue' : IDL.Func([IDL.Nat, IDL.Opt(Clue)], [], []),
  'getAllClueSummaries' : IDL.Func([], [IDL.Vec(ClueSummary)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClueSummary' : IDL.Func([IDL.Nat], [ClueSummary], ['query']),
  'getFirstAvailableClueSummary' : IDL.Func([], [ClueSummary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reassignClueId' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAnswer' : IDL.Func([IDL.Nat, IDL.Text], [AnswerResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Media = IDL.Variant({
    'imageUrl' : IDL.Text,
    'pptUrl' : IDL.Text,
    'videoUrl' : IDL.Text,
  });
  const Clue = IDL.Record({
    'id' : IDL.Nat,
    'media' : IDL.Opt(Media),
    'title' : IDL.Text,
    'statement' : IDL.Text,
    'answer' : IDL.Text,
  });
  const ClueSummary = IDL.Record({
    'id' : IDL.Nat,
    'media' : IDL.Opt(Media),
    'title' : IDL.Text,
    'statement' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const AnswerResult = IDL.Record({
    'correct' : IDL.Bool,
    'nextClueId' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllClues' : IDL.Func([], [], []),
    'createClue' : IDL.Func([Clue], [], []),
    'deleteClue' : IDL.Func([IDL.Nat], [], []),
    'editClue' : IDL.Func([IDL.Nat, IDL.Opt(Clue)], [], []),
    'getAllClueSummaries' : IDL.Func([], [IDL.Vec(ClueSummary)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClueSummary' : IDL.Func([IDL.Nat], [ClueSummary], ['query']),
    'getFirstAvailableClueSummary' : IDL.Func([], [ClueSummary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reassignClueId' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAnswer' : IDL.Func([IDL.Nat, IDL.Text], [AnswerResult], []),
  });
};

export const init = ({ IDL }) => { return []; };